<a href="https://colab.research.google.com/github/suyash-sm/Valorant/blob/master/Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary libraries
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load the data into a pandas dataframe
df = pd.read_csv('afterencoding.csv')


# Create binary columns for each team
df['PlayerTeamWin'] = df.apply(lambda row: 1 if row['Winner'] == row['PlayerTeam'] else 0, axis=1)
df['EnemyTeamWin'] = df.apply(lambda row: 1 if row['Winner'] == row['EnemyTeam'] else 0, axis=1)

# Select the independent and dependent variables






In [ ]:
import numpy as np

In [ ]:
df['KDA'] = (df['Kills'] + df['Assists']) / df['Deaths'].replace(0,1)

In [ ]:
X = df[['GameID', 'Map', 'PlayerName', 'Agent','ACS','KDA','PlayerTeamWin']]
# y = df['PlayerTeamWin']
# Xv=X.iloc[:,:].values
# Yv=y.iloc[:,:].values

In [ ]:
X.head(5)

In [ ]:
Xv=X.iloc[:,:-1].values

In [ ]:
Yv=X.iloc[:,-1].values

In [ ]:
scaler = StandardScaler()
Xv = scaler.fit_transform(Xv)

In [ ]:
print(Xv)

[[ 1.64634663 -0.33605148 -0.21061245 -0.75620716  1.7529336   1.38977343]
 [ 1.64634663 -0.33605148 -1.4215399  -1.20016788  0.3819227   0.9257795 ]
 [ 1.64634663 -0.33605148  0.6029992   1.24161609  0.36598072  1.47999447]
 ...
 [-1.61146372  1.43776211 -1.40382519 -0.09026608 -1.3557539  -1.07061541]
 [-1.61025986 -1.22295828  1.45963231  1.24161609  1.92829546  2.08576431]
 [-1.61025986 -1.22295828 -0.09588857 -0.75620716  1.56162975  0.57778406]]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(Xv, Yv, test_size=0.1, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


lr = LogisticRegression()
lr.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
y_pred = lr.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(acc * 100))

Accuracy: 67.82%


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
y_p= classifier.predict(X_test)
cm = confusion_matrix(y_test, y_p)
print(cm)
accuracy_score(y_test, y_p)

[[8235 1037]
 [3354 1031]]


0.6784799004173684

In [ ]:
print(X)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
import joblib
data=[3045,3,876,10,300,2.6]
data = np.reshape(data, (1, -1))
data=scaler.transform(data)
classifier.predict_proba(data)

array([[0.1, 0.9]])

In [ ]:
import tensorflow as tf
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=32, activation='relu'))
ann.add(tf.keras.layers.Dense(units=16, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 10)


Epoch 1/10
4323/4323 [==============================] - 10s 2ms/step - loss: 0.5973 - accuracy: 0.6798
Epoch 2/10
4323/4323 [==============================] - 11s 2ms/step - loss: 0.5941 - accuracy: 0.6799
Epoch 3/10
4323/4323 [==============================] - 12s 3ms/step - loss: 0.5937 - accuracy: 0.6799
Epoch 4/10
4323/4323 [==============================] - 9s 2ms/step - loss: 0.5934 - accuracy: 0.6799
Epoch 5/10
4323/4323 [==============================] - 9s 2ms/step - loss: 0.5934 - accuracy: 0.6799
Epoch 6/10
4323/4323 [==============================] - 9s 2ms/step - loss: 0.5933 - accuracy: 0.6799
Epoch 7/10
4323/4323 [==============================] - 8s 2ms/step - loss: 0.5931 - accuracy: 0.6799
Epoch 8/10
4323/4323 [==============================] - 9s 2ms/step - loss: 0.5931 - accuracy: 0.6799
Epoch 9/10
4323/4323 [==============================] - 9s 2ms/step - loss: 0.5929 - accuracy: 0.6800
Epoch 10/10
4323/4323 [==============================] - 9s 2ms/step - loss: 0.

In [ ]:
y_pr = ann.predict(X_test)
y_pr = np.where(y_pr > 0.5, 1, 0)

# calculate accuracy
accuracy = accuracy_score(y_test, y_pr)
print(accuracy)

481/481 [==============================] - 1s 1ms/step
0.6819364914107235


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# create a sequential model
model = Sequential()

# add input layer and first hidden layer with 64 neurons and ReLU activation
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))

# add a dropout layer to prevent overfitting
model.add(Dropout(0.2))

# add second hidden layer with 32 neurons and ReLU activation
model.add(Dense(32, activation='relu'))

# add third hidden layer with 16 neurons and ReLU activation
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))

# add output layer with sigmoid activation
model.add(Dense(1, activation='sigmoid'))

# compile the model with binary cross-entropy loss and accuracy metric
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# train the model
model.fit(X_train, y_train, batch_size=32, epochs=10, validation_data=(X_test, y_test))
y_pr=model.predict(X_test)
y_pr = np.where(y_pr > 0.5, 1, 0)

# calculate accuracy
accuracy = accuracy_score(y_test, y_pr)
print(accuracy)

Epoch 1/10
1055/4323 [======>.......................] - ETA: 7s - loss: 0.6052 - accuracy: 0.6799

KeyboardInterrupt: ignored

In [ ]:
y_pr = ann.predict(X_test)
# cm = confusion_matrix(y_test, y_pr)
# print(cm)
# accuracy_score(y_test, y_pr)

1441/1441 [==============================] - 2s 1ms/step


In [ ]:
y_pr = np.where(y_pr > 0.5, 1, 0)

# calculate accuracy
accuracy = accuracy_score(y_test, y_pr)
print(accuracy)

0.6773311931978396
